FROM golang:1.24.2-alpine3.20
WORKDIR /app
COPY go.mod go.sum* ./
RUN go mod download
COPY . .
RUN go install gotest.tools/gotestsum@v1.12.3
RUN CGO_ENABLED=0 go build -o /app/build/testapp ./e2e/testapp
CMD ["gotestsum", "--format", "testname", "--junitfile", "/app/test-results/standard-junit.xml", "--", "-tags", "e2e", "./e2e", "-v", "-timeout", "300s", "-skip", "^(TestRegisterStartupVersion|TestStartupFromExistingOracleState)$"]
