package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"devshard/testenv/config"
)

const composeTmpl = `# Auto-generated by gencompose — do not edit manually.
# Re-generate with: make gen-compose
#
# Phase 6: versiond×N + versiond-router + devshardctl (Phase 7 gateway wiring); keyrings materialized by gencompose.
# Build devshardd before ` + "`make up`" + `:
#   make -C ../.. devshardd-build DEVSHARD_VERSION={{ .Versiond.VersionName }} DEVSHARD_BINARY_VERSION={{ .Versiond.BinaryVersion }}

networks:
  testenv:
    driver: bridge
    ipam:
      config:
        - subnet: {{ .Network.Subnet }}

services:

  mock-chain:
    build:
      context: ../..
      dockerfile: devshard/testenv/Dockerfile.mock-chain
    image: devshard-mock-chain:latest
    environment:
      CONFIG_PATH: "/app/config.yaml"
      MOCK_CHAIN_GRPC_ADDR: ":{{ .MockChain.GRPCPort }}"
      MOCK_CHAIN_RPC_ADDR: ":{{ .MockChain.RPCPort }}"
      MOCK_CHAIN_TESTENV_ADDR: ":{{ .MockChain.TestenvPort }}"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    ports:
      - "{{ .MockChain.GRPCPort }}:{{ .MockChain.GRPCPort }}"
      - "{{ .MockChain.RPCPort }}:{{ .MockChain.RPCPort }}"
      - "{{ .MockChain.TestenvPort }}:{{ .MockChain.TestenvPort }}"
    networks:
      testenv:
        ipv4_address: {{ .Network.BaseIP }}.2
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://127.0.0.1:{{ .MockChain.RPCPort }}/health"]
      interval: 2s
      timeout: 3s
      retries: 30
      start_period: 5s
    restart: unless-stopped

  mock-dapi:
    build:
      context: ../..
      dockerfile: devshard/testenv/Dockerfile.mockdapi
    image: devshard-mock-dapi:latest
    environment:
      MOCK_DAPI_GRPC_ADDR: ":{{ .MockDapi.GRPCPort }}"
      MOCK_DAPI_HTTP_ADDR: ":{{ .MockDapi.HTTPPort }}"
      MOCK_CHAIN_GRPC_ADDR: "{{ .MockChain.Host }}:{{ .MockChain.GRPCPort }}"
      MOCK_CHAIN_RPC_ADDR: "http://{{ .MockChain.Host }}:{{ .MockChain.RPCPort }}"
      MOCK_CHAIN_TESTENV_URL: "http://{{ .MockChain.Host }}:{{ .MockChain.TestenvPort }}"
      MOCK_ML_ENDPOINT: "http://{{ .MockOpenAI.Host }}:{{ .MockOpenAI.HTTPPort }}"
      CHAIN_ID: "{{ .ChainID }}"
    ports:
      - "{{ .MockDapi.GRPCPort }}:{{ .MockDapi.GRPCPort }}"
      - "{{ .MockDapi.HTTPPort }}:{{ .MockDapi.HTTPPort }}"
    networks:
      testenv:
        ipv4_address: {{ .Network.BaseIP }}.3
    depends_on:
      - mock-chain
      - mock-openai
    restart: unless-stopped

  mock-openai:
    build:
      context: ../..
      dockerfile: devshard/testenv/Dockerfile.mockopenai
    image: devshard-mock-openai:latest
    environment:
      MOCK_OPENAI_ADDR: ":{{ .MockOpenAI.HTTPPort }}"
    ports:
      - "{{ .MockOpenAI.HTTPPort }}:{{ .MockOpenAI.HTTPPort }}"
    networks:
      testenv:
        ipv4_address: {{ .Network.BaseIP }}.4
    restart: unless-stopped
{{ if .Postgres.Enabled }}

  devshard-postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: {{ .Postgres.Database }}
      POSTGRES_USER: {{ .Postgres.User }}
      POSTGRES_PASSWORD: {{ .Postgres.Password }}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U {{ .Postgres.User }} -d {{ .Postgres.Database }}"]
      interval: 2s
      timeout: 3s
      retries: 30
    networks:
      testenv:
        ipv4_address: {{ .Postgres.IP }}
    restart: unless-stopped
{{ end }}
{{ range .Hosts }}

  {{ .ID }}:
    build:
      context: ../../versioned
      dockerfile: Dockerfile
    image: devshard-versiond:latest
    environment:
      VERSIOND_ORACLE_URL: http://{{ $.MockDapi.Host }}:{{ $.MockDapi.HTTPPort }}/versions
      VERSIOND_POLL_INTERVAL: "{{ $.Versiond.PollInterval }}"
      VERSIOND_BIN_DIR: /opt/versiond/bin
      VERSIOND_DATA_DIR: /opt/versiond/data
      VERSIOND_BINARY_NAME: devshardd
      VERSIOND_FORCE: "{{ $.Versiond.VersionName }}"
      VERSIOND_OVERRIDE_{{ versionEnvSuffix $.Versiond.VersionName }}: {{ $.Versiond.OverridePath }}
      NODE_GRPC_URL: {{ $.MockChain.Host }}:{{ $.MockChain.GRPCPort }}
      NODE_RPC_URL: http://{{ $.MockChain.Host }}:{{ $.MockChain.RPCPort }}
      NODE_HOST: {{ $.MockChain.Host }}
      NODE_MANAGER_ADDR: {{ $.MockDapi.Host }}:{{ $.MockDapi.GRPCPort }}
      CHAIN_ID: "{{ $.ChainID }}"
      KEYRING_BACKEND: file
      KEYRING_DIR: {{ $.Versiond.KeyringDir }}
      KEYRING_PASSWORD: ${TESTENV_KEYRING_PASSWORD:-{{ $.Versiond.KeyringPassword }}}
      KEY_NAME: {{ .ID }}
      DEVSHARD_OTEL_ENABLED: ${TESTENV_OTEL_ENABLED:-false}
      OTEL_ENDPOINT: ${TESTENV_OTEL_ENDPOINT:-}
{{ if eq $.Versiond.Mode "multi" }}
      DEVSHARD_REQUIRE_POSTGRES: "1"
{{ end }}
{{ if $.Postgres.Enabled }}
      PGHOST: {{ $.Postgres.Host }}
      PGPORT: "{{ $.Postgres.Port }}"
      PGDATABASE: {{ $.Postgres.Database }}
      PGUSER: {{ $.Postgres.User }}
      PGPASSWORD: {{ $.Postgres.Password }}
{{ end }}
    volumes:
      - {{ $.Versiond.HostBinaryMount }}:{{ $.Versiond.OverridePath }}:ro
      - ./keyring:{{ $.Versiond.KeyringDir }}
      - ./data/{{ .ID }}:/opt/versiond/data
    networks:
      testenv:
        ipv4_address: {{ .IP }}
    depends_on:
{{ if $.Postgres.Enabled }}
      mock-chain:
        condition: service_healthy
      mock-dapi:
        condition: service_started
      mock-openai:
        condition: service_started
      devshard-postgres:
        condition: service_healthy
{{ if eq .ID "versiond-1" }}
      versiond-0:
        condition: service_started
{{ end }}
{{ else }}
      - mock-chain
      - mock-dapi
      - mock-openai
{{ end }}
    restart: unless-stopped
{{ end }}

  versiond-router:
    build:
      context: ../../versiond-router
      dockerfile: Dockerfile
    image: devshard-versiond-router:latest
    environment:
      VERSIOND_HOSTS: "{{ versiondHosts . }}"
      VERSIOND_PORT: "8080"
    ports:
      - "{{ .VersiondRouter.Port }}:8080"
    networks:
      testenv:
        ipv4_address: {{ .VersiondRouter.IP }}
    depends_on:
{{ range .Hosts }}
      - {{ .ID }}
{{ end }}
    restart: unless-stopped

  devshardctl:
    build:
      context: ../..
      dockerfile: devshard/Dockerfile
      target: devshardctl-runtime
      args:
        DEVSHARD_VERSION: "{{ .Versiond.VersionName }}"
    image: devshard-runtime:latest
    entrypoint: ["devshardctl"]
    environment:
      DEVSHARD_PORT: "{{ .Devshardctl.Port }}"
      DEVSHARD_CHAIN_GRPC: {{ .MockChain.Host }}:{{ .MockChain.GRPCPort }}
      DEVSHARD_NODE_MANAGER_ADDR: {{ .MockDapi.Host }}:{{ .MockDapi.GRPCPort }}
      DEVSHARD_CHAIN_ID: "{{ .ChainID }}"
      DEVSHARD_PUBLIC_API: http://{{ .MockDapi.Host }}:{{ .MockDapi.HTTPPort }}
      DEVSHARD_ESCROW_ID: "{{ primaryEscrowID . }}"
      DEVSHARD_MODEL: "{{ primaryModelID . }}"
      DEVSHARD_PRIVATE_KEY: ${TESTENV_USER_PRIVATE_KEY}
      DEVSHARD_ADMIN_API_KEY: ${TESTENV_ADMIN_API_KEY}
      DEVSHARD_STORAGE_DIR: /var/lib/devshardctl
      GATEWAY_MAX_TOKENS_CAP: "4096"
    volumes:
      - ./data/devshardctl:/var/lib/devshardctl
    ports:
      - "{{ .Devshardctl.Port }}:{{ .Devshardctl.Port }}"
    networks:
      testenv:
        ipv4_address: {{ .Devshardctl.IP }}
    depends_on:
      mock-chain:
        condition: service_healthy
      mock-dapi:
        condition: service_started
      versiond-router:
        condition: service_started
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://127.0.0.1:{{ .Devshardctl.Port }}/v1/status"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 30s
    restart: unless-stopped
`

func writeCompose(cfg *config.File, outPath string) error {
	funcs := template.FuncMap{
		"versionEnvSuffix": versionEnvSuffix,
		"versiondHosts":    versiondHosts,
		"primaryEscrowID":  primaryEscrowID,
		"primaryModelID":   primaryModelID,
	}
	tmpl, err := template.New("compose").Funcs(funcs).Parse(composeTmpl)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil && filepath.Dir(outPath) != "." {
		return fmt.Errorf("mkdir: %w", err)
	}
	f, err := os.Create(outPath)
	if err != nil {
		return fmt.Errorf("create %s: %w", outPath, err)
	}
	defer f.Close()
	if err := tmpl.Execute(f, cfg); err != nil {
		return fmt.Errorf("execute template: %w", err)
	}
	return nil
}

func writeEnvFile(cfg *config.File, outPath string) error {
	var b strings.Builder
	b.WriteString("# Auto-generated by gencompose — do not edit manually.\n")
	b.WriteString(fmt.Sprintf("TESTENV_CHAIN_ID=%s\n", cfg.ChainID))
	b.WriteString(fmt.Sprintf("TESTENV_USER_PRIVATE_KEY=%s\n", cfg.User.PrivateKeyHex))
	b.WriteString(fmt.Sprintf("TESTENV_ADMIN_API_KEY=%s\n", config.DefaultAdminAPIKey))
	b.WriteString(fmt.Sprintf("TESTENV_KEYRING_PASSWORD=%s\n", cfg.Versiond.KeyringPassword))
	b.WriteString("TESTENV_OTEL_ENABLED=false\n")
	b.WriteString("TESTENV_OTEL_ENDPOINT=\n")
	return os.WriteFile(outPath, []byte(b.String()), 0o600)
}

func versionEnvSuffix(versionName string) string {
	return strings.ReplaceAll(versionName, ".", "_")
}

func versiondHosts(cfg *config.File) string {
	names := make([]string, len(cfg.Hosts))
	for i, h := range cfg.Hosts {
		names[i] = h.ID
	}
	return strings.Join(names, " ")
}

func primaryEscrowID(cfg *config.File) string {
	return config.PrimaryEscrowID(cfg)
}

func primaryModelID(cfg *config.File) string {
	return config.PrimaryModelID(cfg)
}
